const fallBack = {
  "robinUrl":"",
  "widget0_enableBundit":{
    "cp_ensemble":true,
    "details":true,
    "duplicates":true,
    "fields":[
      "id",
      "product_id",
      "category",
      "ontology",
      "link",
      "image_link",
      "internal_image_url",
      "small_image_link",
      "msd_ontology"
    ],
    "num_results":[
      15
    ],
    "require_source":true,
    "widget_list":[
      0
    ],
    "use_bandits":true,
    "brand_filter":false,
    "is_from_demo_site":true,
    "force_debug":true
  },
  "widget0_disableBundit":{
    "cp_ensemble":true,
    "details":true,
    "duplicates":true,
    "fields":[
      "id",
      "product_id",
      "category",
      "ontology",
      "link",
      "image_link",
      "internal_image_url",
      "small_image_link",
      "msd_ontology"
    ],
    "num_results":[
      15
    ],
    "require_source":true,
    "widget_list":[
      0
    ],
    "use_bandits":false,
    "brand_filter":false,
    "is_from_demo_site":true,
    "force_debug":true
  },
  "widget9":{
    "cp_ensemble":"false",
    "details":true,
    "fields":[
      "id",
      "product_id",
      "category",
      "ontology",
      "link",
      "image_link",
      "internal_image_url",
      "small_image_link",
      "msd_ontology"
    ],
    "num_results":4,
    "group_by_occasion":true,
    "widget_list":[
      9
    ],
    "manually_curated":"false",
    "out_of_stock_fallback":"fill",
    "machine_generated_fallback":"true",
    "is_from_demo_site":true
  }
}

export default fallBack;