const cardStyleConfig = {
  card: {
    orientation: {
      horizontal: false,
    },
    cards_per_row: 4,
    show_meta_data: false,
    showWishListButton: true,
    showAddToCartButton: true,
    metaData: [],
  },
  image: {
    backgroundColor: "#fff",
    height: "",
    width: "",
  },
  text_container: {
    backgroundColor: "#fff",
    height: "",
    width: "",
    alignItems: "",
    justifyContent: "",
    stretchItems: false,
  },
  title: {
    fontSize: "14",
    fontFamily: "Poppins_Semi_Bold",
    textAlign: "center",
    color: "#333",
    lineHeight: "18",
    fontWeight: "600",
    margin_top: "5",
    margin_right: "3",
    margin_bottom: "5",
    margin_left: "3",
    padding_top: "",
    padding_right: "",
    padding_bottom: "",
    padding_left: "",
    restrictLines: 2,
    minHeight: "55",
    onHover: {
      textDecoration: "underline",
      color: "#333",
    },
  },
  price: {
    fontSize: "13",
    fontFamily: "Open_Sans_Regular",
    textAlign: "center",
    color: "#333",
    margin_top: "",
    margin_right: "",
    margin_bottom: "",
    margin_left: "",
    padding_top: "2",
    padding_right: "2",
    padding_bottom: "2",
    padding_left: "2",
    restrictLines: "",
    minHeight: "40",
  },
  primary_button: {
    fontSize: "11.5px",
    textTransform: "uppercase",
    backgroundColor: "#2862FF",
    color: "#fff",
    restrictLines: "",
  },
  secondary_button: {
    fontSize: "11.5px",
    textTransform: "uppercase",
    backgroundColor: "#fff",
    color: "#333",
    restrictLines: "",
  },
};

export { cardStyleConfig };
